yshima42/ft_transcendence

- frontend/src/components/pages/Login.tsx
- frontend/src/router/Router.tsx
一旦作り切りたすぎて認証作りました。とりあえず一旦これは置いてチュートリアルやります。
> feat: 簡易認証機能実装(user-listのみ管理)

- backend/src/auth/auth.module.ts
- backend/src/auth/auth.service.ts
- backend/src/auth/strategy/jwt.strategy.ts
- backend/src/user/test/user.service.spec.ts
- backend/src/user/user.controller.ts
- backend/src/user/user.module.ts
- backend/src/user/user.service.spec.ts
- backend/src/user/user.service.ts
テストを作ってみたかったので、申し訳程度にやってみました。
テストのために、インポートパスを相対パスに修正しました。
findAllの正常系のテストを作成しました。
> user.serviceのテストを作成しました。

- frontend/src/App.tsx
- frontend/src/components/pages/Login.tsx
- frontend/src/router/ProtectedRoutes.tsx
- frontend/src/router/PublicRoutes.tsx
- frontend/src/router/Router.tsx
routingのところをリファクタリングしました。
routingにはroutingだけ置いて、publicとprotectedをいい感じに。
> chore: routerをbulletproof-react参考にリファクタリング

- frontend/src/App.tsx
- frontend/src/components/pages/Login.tsx
- frontend/src/router/ProtectedRoutes.tsx
- frontend/src/router/PublicRoutes.tsx
- frontend/src/router/Router.tsx
Reverts yshima42/ft_transcendence#15
> Revert "chore: routerをbulletproof-react参考にリファクタリング"

- frontend/src/App.tsx
- frontend/src/components/pages/Login.tsx
- frontend/src/router/ProtectedRoutes.tsx
- frontend/src/router/PublicRoutes.tsx
- frontend/src/router/Router.tsx
Reverts yshima42/ft_transcendence#16
> Revert "Revert "chore: routerをbulletproof-react参考にリファクタリング""

- backend/src/user/user.controller.ts
- backend/src/user/user.service.ts
Bodyにnameを与えて、DBからそのnameに一致するユーザーの情報を返すfindOne(/user/find)APIを作成しました。
> feat: 特定のユーザー情報を返すAPIを作成しました。

- backend/src/app.module.ts
- backend/src/auth/auth.controller.ts
- backend/src/auth/auth.service.ts
- backend/src/auth/strategy/ft.strategy.ts
- backend/src/auth/strategy/jwt.strategy.ts
- backend/src/users/test/users.service.spec.ts
- backend/src/users/users.controller.ts
- backend/src/users/users.module.ts
- backend/src/users/users.service.ts
- user module を users module に変更。
- auth をリファクタリング。
> User account/backend/users new

- frontend/src/components/molecules/UserNavigation.tsx
- frontend/src/features/users/routes/Profile.tsx
- frontend/src/features/users/routes/index.tsx
ひとまず、フロント側でモックデータを使ってプロフィール画面を表示するようにしました。ゲームの勝敗数、試合履歴の部分を表示しました。
> chore: profile画面を作成。

- backend/prisma/migrations/20221118074855_add_user_attr/migration.sql
- backend/prisma/schema.prisma
- backend/prisma/seed.ts
- backend/src/app.module.ts
- backend/src/auth/interfaces/signup-user.interface.ts
- backend/src/game/game.controller.ts
- backend/src/profile/dto/update-user.dto.ts
- backend/src/profile/profile.controller.ts
- backend/src/profile/profile.module.ts
- backend/src/profile/profile.service.ts
- backend/src/users/dto/user.dto.ts
- backend/src/users/interfaces/update-user-columns.interface.ts
- backend/src/users/users.controller.ts
- backend/src/users/users.module.ts
- backend/src/users/users.service.ts
以下のエンドポイントを作成しました。
- ユーザー情報の取得
GET /users/:id/profile -> すべての情報が返る
GET /users/:id/profile?fields=id,name,onlineStatus
- ユーザーのアバター取得
GET /users/:id/profile/avatar/:filename
- マッチ履歴一覧取得
GET /users/:id/game/matches
- 戦績取得
GET /users/:id/game/stats
- アバター
profileモジュールに入れました
- アップロード
POST /profile/avatar
- アバター取得
GET /profile/avatar/:filename
- ユーザー情報(プロフィールに関するもの)
- 情報の更新
- POST /profile
- bodyにjson形式で記述
- avatarはとりあえず別のエンドポイントで対応。
できたら統一する
- 情報の取得
- GET /profile -> すべての情報が返る
- GET /profile?fields=id,name,onlineStatus
- fields
- id
- name
- avatarUrl
- onlineStatus (ONLINE | OFFLINE | INGAME)
- nickname
- MatchHistory
- マッチ履歴一覧取得
GET /game/matches
- 戦績取得
GET /game/stats
- マッチ履歴作成
POST /game/matches
※リアルタイム通信のときに考える。現状はブラウザから2回POSTする
- body
- userId
- opponentId
- userScore
- opponentScore …
> User account/backend/endpoint

- backend/src/friendships/friendships.controller.ts
- backend/src/friendships/friendships.service.ts
- backend/test.sh
リファクターできる部分まだありますが、設計変えそうですし一旦これでいいかなと思っています。
関数の順番変えたから、変更点わかりにくくなってしまいました。
> feat: friendshipsのエンドポイントの修正

- backend/.eslintrc.json
- backend/nest-cli.json
- backend/package.json
- backend/src/auth/auth.controller.ts
- backend/src/auth/dto/dummy-login.dto.ts
- backend/src/friendships/dto/update-relationship.dto.ts
- backend/src/friendships/entities/relationship.entity.ts
- backend/src/friendships/friendships.controller.ts
- backend/src/game/dto/match-result.dto.ts
- backend/src/game/entities/game-stats.entity.ts
- backend/src/game/entities/match-result.entity.ts
- backend/src/game/game.controller.ts
- backend/src/main.ts
- backend/src/profile/dto/update-user.dto.ts
- backend/src/profile/profile.controller.ts
- backend/src/users/dto/user.dto.ts
- backend/src/users/entities/user.entity.ts
- backend/src/users/users.controller.ts
- backend/yarn.lock
Swaggerを導入しました
```
yarn
yarn start:dev
http://localhost:3000/apiにブラウザからアクセス
```
cookieを保存してswaggerのUIからapiを叩けるようにする。
現状はログインしかできません。
[チャット バックエンド　Swagger導入 \- HackMD](https://hackmd.io/@yshima/chat_backend#Swagger%E5%B0%8E%E5%85%A5)
> User account/backend/swagger

- frontend/package.json
- frontend/src/features/users/components/BlockUsersList.tsx
- frontend/src/features/users/components/FriendsList.tsx
- frontend/src/features/users/components/UsersList.tsx
- frontend/src/features/users/components/UsersTabButton.tsx
- frontend/src/features/users/hooks/useAllBlock.ts
- frontend/src/features/users/hooks/useAllFriends.ts
- frontend/src/features/users/hooks/useAllUsers.ts
- frontend/src/features/users/routes/Profile.tsx
- frontend/src/features/users/routes/ReactQuery.tsx
- frontend/src/features/users/routes/Users.tsx
- frontend/src/features/users/routes/index.tsx
- frontend/src/lib/sleep.ts
- frontend/src/providers/AppProvider.tsx
- frontend/yarn.lock
UsersページにTransition, Suspenseの機能を追加しました。
> UsersページにReact18の機能を追加しました。

- backend/prisma/migrations/20221121071028_add_block/migration.sql
- backend/prisma/schema.prisma
- backend/prisma/seed.ts
- backend/src/friendships/dto/create-relationship.dto.ts
- backend/src/friendships/entities/relationship.entity.ts
- backend/src/friendships/friendships.controller.ts
- backend/src/friendships/friendships.service.ts
いかがでしょう！
エッジケース抜けてる可能性あるのでまた確認しましょう。
> User account/backend/block

- .github/workflows/test.yml
- backend/prisma/migrations/20221127055250_add_win/migration.sql
- backend/prisma/schema.prisma
- backend/src/game/dto/match-result.dto.ts
- backend/src/game/entities/match-result.entity.ts
- backend/src/game/game.service.ts
yarn start:devで起動しないバグを修正しました。
#65 でschimaを変更したにもかかわらず、ソースコードを変更しなかったことが原因でした。
> fix: yarn start:devで起動しないバグを修正した

- .github/ISSUE_TEMPLATE/config.yml
ごめんなさい。projectの仕様が新しくなっていて動かなかったので一旦削除します。
> project自動化は古いproject用で動かなかったので削除

- frontend/src/features/profile/components/BlockButton.tsx
- frontend/src/features/profile/components/UserInfoCard.tsx
- frontend/src/features/profile/routes/Profile.tsx
- frontend/src/hooks/api/generics/useDeleteApi.ts
- frontend/src/hooks/api/generics/usePatchApi.ts
- frontend/src/hooks/api/generics/usePostApi.ts
- frontend/src/hooks/api/relations/useUserBlock.ts
- frontend/src/hooks/api/relations/useUserBlockCancel.ts
#167 
プロフィールページにブロック/ブロック解除のUIを導入しました。
> User account/block　ユーザーをブロックできる

- backend/package.json
- pre-commit に、./linst-staged-each.sh 移動しました。
- 全てフォーマット、リントかけましたが、すべて問題なかったです！
> lint-staged 変更

- backend/src/game/game.class.ts
- backend/src/game/game.gateway.ts
- frontend/src/features/game/components/JoinRoom.tsx
- frontend/src/features/game/components/PongGame.tsx
- frontend/src/features/game/routes/GameTop.tsx
- frontend/src/features/game/utils/gameContext.ts
- frontend/src/features/game/utils/gameService.ts
バックエンド
- gameRoom の型に、paddle1,paddle2,ball を追加。
フロントエンド
- context に、roomName を追加
> 複数のgameroom を持つようにした

- frontend/src/features/game/components/JoinRoom.tsx
- frontend/src/features/game/components/PongGame.tsx
- frontend/src/features/game/hooks/useGame.ts
- frontend/src/features/game/routes/Top.tsx
Reverts yshima42/ft_transcendence#216
ゲームが動かなくなっていたので一旦revertします。
> Revert "useGame"

- backend/src/socket/socket.gateway.ts
- frontend/src/features/game/hooks/useGameInviting.ts
- frontend/src/providers/InvitationAlert.tsx
- frontend/src/providers/SocketProvider.tsx
- ゲームに招待された時にどこのページにいても招待されましたのポップアップが出るように
- 招待をdeclineしたら相手にdeclineが伝わるように（toastのwarningで表示）
- フロント、バックでuserIdToRoomIdを作ってGameボタンの表示の変更
> ゲーム招待される時に１ページ挟む

- backend/prisma/schema.prisma
- backend/prisma/seed.ts
- backend/src/__tests__/friend-requests.service.spec.ts
- frontend/prisma/schema.prisma
issueに上がっていた以下のバグを、seed.tsを修正して解消しました。
・Friendタブに表示されないユーザーがいる。
・dummy1がdummy1をブロックしている。
・dummy3のFriendタブにdummy1が存在しない。
close #171 
close #224
> Friendページでのバグを修正。

- frontend/Dockerfile
本番環境でreactQueryDevtoolsを表示させないようにしました。
> chore: 本番環境でreactQueryDevtoolsを表示させない

- backend/.eslintrc.json
- backend/src/auth/auth.controller.ts
- backend/src/auth/filter/login-http-exception.filter.ts
- backend/src/users/users.controller.ts
やったこと
- Login は、Link でバックエンドに飛んでくるので、例外が起きた場合、フロントに帰らない。
- 例外フィルターを使って、例外起きた場合は、ログインページにリダイレクトするようにした。
- 試し方：バックエンドのログイン処理の部分 で意図的に例外起こす！
参考サイト　https://docs.nestjs.com/exception-filters 
- avatarImageUrl の更新が終わってから、古いavatarImage を削除するようにした。
> Bug fix/login error

- backend/src/socket/socket.gateway.ts
- ログアウトしたあと、戻るボタンでバックエンドが落ちるバグを修正
- 以下は保存したら自動整形されました。
```
(gameRoom: GameRoom) => {
this.deleteGameRoom(gameRoom);
},
```
> socketの認証エラーのエラーハンドリング記述

- backend/src/friend-requests/friend-requests.service.ts
> findRequestableUsersをソート。
